export enum Permission {
  // Profile
  PROFILE_VIEW = 'PROFILE_VIEW',
  PROFILE_UPDATE = 'PROFILE_UPDATE',
  
  // Leave
  LEAVE_CREATE = 'LEAVE_CREATE',
  LEAVE_VIEW_OWN = 'LEAVE_VIEW_OWN',
  LEAVE_VIEW_ALL = 'LEAVE_VIEW_ALL',
  LEAVE_APPROVE = 'LEAVE_APPROVE',
  LEAVE_REJECT = 'LEAVE_REJECT',
  
  // Payslip
  PAYSLIP_VIEW = 'PAYSLIP_VIEW',
  PAYSLIP_VIEW_ALL = 'PAYSLIP_VIEW_ALL',
  
  // Documents
  DOC_VIEW = 'DOC_VIEW',
  DOC_UPLOAD = 'DOC_UPLOAD',
  DOC_VALIDATE = 'DOC_VALIDATE',
  
  // Sanctions
  SANCTION_VIEW = 'SANCTION_VIEW',
  SANCTION_CREATE = 'SANCTION_CREATE',
  SANCTION_VIEW_ALL = 'SANCTION_VIEW_ALL',
  
  // Explanation Requests
  EXPLANATION_REQUEST_VIEW = 'EXPLANATION_REQUEST_VIEW',
  EXPLANATION_REQUEST_RESPOND = 'EXPLANATION_REQUEST_RESPOND',
  EXPLANATION_REQUEST_VIEW_ALL = 'EXPLANATION_REQUEST_VIEW_ALL',
  
  // Team & Employees
  TEAM_VIEW = 'TEAM_VIEW',
  EMPLOYEE_VIEW = 'EMPLOYEE_VIEW',
  EMPLOYEE_VIEW_ALL = 'EMPLOYEE_VIEW_ALL',
  EMPLOYEE_CREATE = 'EMPLOYEE_CREATE',
  EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE',
  EMPLOYEE_SUSPEND = 'EMPLOYEE_SUSPEND',
  
  // Reports
  REPORT_VIEW = 'REPORT_VIEW',
  REPORT_EXPORT = 'REPORT_EXPORT',
  
  // Contracts
  CONTRACT_VIEW = 'CONTRACT_VIEW',
  CONTRACT_CREATE = 'CONTRACT_CREATE',
  CONTRACT_UPDATE = 'CONTRACT_UPDATE',
  CONTRACT_DELETE = 'CONTRACT_DELETE',
  
  // Recruitment
  RECRUITMENT_VIEW = 'RECRUITMENT_VIEW',
  RECRUITMENT_CREATE = 'RECRUITMENT_CREATE',
  RECRUITMENT_UPDATE = 'RECRUITMENT_UPDATE',
  
  // Announcements
  ANNOUNCEMENT_VIEW = 'ANNOUNCEMENT_VIEW',
  ANNOUNCEMENT_CREATE = 'ANNOUNCEMENT_CREATE',
  ANNOUNCEMENT_UPDATE = 'ANNOUNCEMENT_UPDATE',
  ANNOUNCEMENT_DELETE = 'ANNOUNCEMENT_DELETE',
  
  // Dashboard
  DASHBOARD_VIEW = 'DASHBOARD_VIEW',
  DASHBOARD_MANAGE = 'DASHBOARD_MANAGE',
}

export const PERMISSION_GROUPS = {
  PROFILE: ['PROFILE_VIEW', 'PROFILE_UPDATE'],
  LEAVE: ['LEAVE_CREATE', 'LEAVE_VIEW_OWN', 'LEAVE_VIEW_ALL', 'LEAVE_APPROVE', 'LEAVE_REJECT'],
  PAYSLIP: ['PAYSLIP_VIEW', 'PAYSLIP_VIEW_ALL'],
  DOCUMENT: ['DOC_VIEW', 'DOC_UPLOAD', 'DOC_VALIDATE'],
  SANCTION: ['SANCTION_VIEW', 'SANCTION_CREATE', 'SANCTION_VIEW_ALL'],
  EXPLANATION: ['EXPLANATION_REQUEST_VIEW', 'EXPLANATION_REQUEST_RESPOND', 'EXPLANATION_REQUEST_VIEW_ALL'],
  EMPLOYEE: ['TEAM_VIEW', 'EMPLOYEE_VIEW', 'EMPLOYEE_VIEW_ALL', 'EMPLOYEE_CREATE', 'EMPLOYEE_UPDATE', 'EMPLOYEE_SUSPEND'],
  REPORT: ['REPORT_VIEW', 'REPORT_EXPORT'],
  CONTRACT: ['CONTRACT_VIEW', 'CONTRACT_CREATE', 'CONTRACT_UPDATE', 'CONTRACT_DELETE'],
  RECRUITMENT: ['RECRUITMENT_VIEW', 'RECRUITMENT_CREATE', 'RECRUITMENT_UPDATE'],
  ANNOUNCEMENT: ['ANNOUNCEMENT_VIEW', 'ANNOUNCEMENT_CREATE', 'ANNOUNCEMENT_UPDATE', 'ANNOUNCEMENT_DELETE'],
};